environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn test

# Don't actually build.
build: off
