// @ts-check

/** @type {import('create-stylable-app').TemplateDefinition} */
module.exports = {
    dependencies: ['react', 'react-dom'],
    devDependencies: [
        '@rollup/plugin-commonjs',
        '@rollup/plugin-html',
        '@rollup/plugin-image',
        '@rollup/plugin-node-resolve',
        '@rollup/plugin-replace',
        '@rollup/plugin-typescript',
        '@stylable/cli',
        '@stylable/rollup-plugin',
        '@stylable/runtime',
        '@types/react',
        '@types/react-dom',
        '@typescript-eslint/eslint-plugin',
        '@typescript-eslint/parser',
        'eslint',
        'eslint-config-prettier',
        'eslint-plugin-react',
        'eslint-plugin-react-hooks',
        'rimraf',
        'rollup',
        'rollup-plugin-copy',
        'rollup-plugin-serve',
        'serve',
        'typescript',
    ],
    packageJson: {
        description: 'Stylable App',
        private: true,
        license: 'UNLICENSED',
        type: 'module',
        scripts: {
            clean: 'rimraf dist',
            prebuild: 'npm run clean',
            build: 'rollup -c --environment NODE_ENV:production',
            start: 'rollup -c -w',
            serve: 'serve ./dist',
            lint: 'eslint .',
            typecheck: 'tsc --noEmit',
            test: 'npm run typecheck && npm run lint',
        },
    },
    postinstall: [['npm', 'run', 'build']],
};
