name: Bug Report
description: File a bug report
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually went wrong
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you wanted to see!
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Stylable are you running?
      placeholder: ex. @stylable/core@4.5.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Describe any additional context you think is related
