export { StylableWebpackPlugin, StylableWebpackPluginOptions } from './plugin.js';
export {
    OptimizationMapping,
    createCalcDepthContext,
    createDecacheRequire,
    createOptimizationMapping,
    createStaticCSS,
    createStylableResolverCacheMap,
    emitCSSFile,
    extractDataUrlFromAssetModuleSource,
    extractFilenameFromAssetModule,
    findIfStylableModuleUsed,
    getCSSViewModuleWebpack,
    getEntryPointModules,
    getFileName,
    getOnlyChunk,
    getSortedModules,
    getStaticPublicPath,
    getWebpackBuildMeta,
    getStylableBuildData,
    getStylableBuildMeta,
    getStylableModules,
    getTopLevelInputFilesystem,
    injectLoader,
    isAssetModule,
    isDependencyOf,
    isLoadedWithKnownAssetLoader,
    isSameResourceModule,
    isStylableModule,
    outputOptionsAwareHashContent,
    provideStylableModules,
    replaceCSSAssetPlaceholders,
    replaceMappedCSSAssetPlaceholders,
    reportNamespaceCollision,
    staticCSSWith,
    uniqueFilterMap,
} from './plugin-utils.js';
export { getImports, getReplacementToken } from './loader-utils.js';
export {
    applyWebpackConfigStylableExcludes,
    bundleServerLibs,
} from './webpack-config-stylable-excludes.js';
export {
    BuildData,
    CompilationParams,
    DependencyTemplates,
    EntryPoint,
    LoaderData,
    NormalModuleFactory,
    RuntimeTemplate,
    StringSortableSet,
    StylableBuildMeta,
    StylableLoaderContext,
    WebpackCreateHash,
    WebpackOutputOptions,
} from './types.js';
export { createWebpackResolver } from './legacy-module-resolver.js';
