name: release3
on:
  push:
    branches: ['3.x']
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn
      - run: npm i -g yarn@1
      - run: yarn config set network-timeout 300000
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npx pleb@5 publish --tag release-3.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
