name: npm

on:
  push:
    branches: ['3.x']

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'
      - run: npm i -g yarn@1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: npx pleb publish --tag release-3.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
